train_args:
  output_dir: "output"
  evaluation_strategy: "epoch"
  save_strategy: "No"
  learning_rate: 0.00005
  weight_decay: 0.01
  num_train_epochs: 3
  seed: 42
  logging_strategy: "epoch"
  save_strategy: "no"
  fp16: True
  full_determinism: False
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  load_best_model_at_end: False
  disable_tqdm: True
#   batch_eval_metrics: None
batch_size: 16